export const QUESTIONNAIRES = {
  pretest: {
    id: "pretest",
    title: "2Phishy: Pre-test Assessment",
    subtitle: "Baseline cybersecurity awareness before using the 2Phishy application.",
    intro: [
      "We are third-year BS Information Technology students from Mapúa University – Makati Campus conducting our thesis entitled \"2Phishy: A Gamified Learning Application for Cybersecurity Awareness.\"",
      "Thank you for participating in this pre-playtest assessment. This questionnaire aims to measure your current cybersecurity awareness, experiences with online scams, and ability to recognize common scam scenarios before using the 2Phishy application.",
      "Please answer each question honestly based on your own knowledge and experience.",
    ],
    completionCopy:
      "Your pre-test response has been saved to the research backend and queued for Google Forms backup.",
    googleFormsEndpoint:
      "https://docs.google.com/forms/d/e/1FAIpQLSd0R0egqnpZtpO5jHGFuV0Nv_wDr_IFCNtVwpXDqAkJBaMU5Q/formResponse",
    steps: [
      {
        id: "consent",
        title: "Data Privacy Agreement",
        questions: [
          {
            id: "consent",
            entry: "entry.511338609",
            googleFormsEntry: "entry.511338609_sentinel",
            question:
              "I am aware of my rights and the responsibilities of the researchers regarding the management of my data. I hereby grant permission for this group's researchers to use the information I will provide on this form for the purposes of this study.",
            type: "radio",
            required: true,
            choices: ["I agree with terms and conditions outlined above"],
          },
        ],
      },
      {
        id: "participant-profile",
        title: "Participant Profile",
        questions: [
          {
            id: "participant_id",
            entry: "entry.907467691",
            question: "Participant ID",
            type: "short_answer",
            required: true,
            placeholder: "Please ask the facilitator if unknown",
            helperText: "If you are unsure, ask the facilitator before continuing.",
          },
          {
            id: "age",
            entry: "entry.966320300",
            question: "Age",
            type: "short_answer",
            required: true,
            inputType: "number",
            placeholder: "Example: 20",
            helperText: "Enter a whole number only.",
          },
          {
            id: "internet_usage",
            entry: "entry.1511657596",
            question: "What is your average internet usage per day?",
            type: "radio",
            required: true,
            choices: [
              "Less than 1 hour",
              "1 to 3 hours",
              "3 to 6 hours",
              "6 to 9 hours",
              "Greater than 9 hours",
            ],
          },
          {
            id: "school_department",
            entry: "entry.1045391551",
            googleFormsOtherValue: "__other_option__",
            question: "What is your school department?",
            type: "radio",
            required: false,
            choices: [
              "School of Information Technology",
              "School of Media Studies",
              "School of Nursing",
              "School of Health Sciences",
              "School of Business",
              "Other",
            ],
          },
          {
            id: "cyber_training",
            entry: "entry.439680690",
            question: "Have you previously received any formal education or training related to cybersecurity?",
            type: "radio",
            required: false,
            choices: ["Yes", "No"],
          },
        ],
      },
      {
        id: "baseline-knowledge",
        title: "CyberSecurity Section 2: Baseline Cybersecurity Knowledge Assessment",
        questions: [
          {
            id: "phishing_url",
            entry: "entry.1673979401",
            question: "Which URL is most likely a phishing website?",
            type: "radio",
            required: true,
            choices: [
              "www.microsoft.com",
              "www.paypal-login.com",
              "www.google.com",
              "www.mapua.edu.ph",
            ],
          },
          {
            id: "strongest_password",
            entry: "entry.629643857",
            question: "Which password is the strongest?",
            type: "radio",
            required: true,
            choices: ["Password123", "Qwert2025", "my$ecurePassw0rd!", "Abc12345"],
          },
          {
            id: "verify_email",
            entry: "entry.1958849132",
            question:
              "You receive an unexpected email asking you to verify your account by clicking a link. What should you do?",
            type: "radio",
            required: true,
            choices: [
              "Click the link immediately",
              "Verify through the official website first",
              "Reply with your information",
              "Forward the email to friends",
            ],
          },
          {
            id: "malware_infection",
            entry: "entry.70721282",
            question: "How does malware most commonly infect computers?",
            type: "radio",
            required: true,
            choices: [
              "Operating system updates",
              "Suspicious downloads or email attachments",
              "Changing desktop wallpaper",
              "Restarting the computer",
            ],
          },
          {
            id: "it_support",
            entry: "entry.527102369",
            question: "Someone claiming to be IT support asks for your password. What should you do?",
            type: "radio",
            required: true,
            choices: [
              "Give your password",
              "Verify their identity before sharing anything",
              "Ignore all IT staff",
              "Change your username",
            ],
          },
          {
            id: "public_info",
            entry: "entry.1904816629",
            question: "Which information should generally NOT be shared publicly?",
            type: "radio",
            required: true,
            choices: [
              "Favorite movie",
              "Phone number and home address",
              "Favorite food",
              "School subject",
            ],
          },
          {
            id: "infected_device",
            entry: "entry.1048288850",
            question: "If you believe your computer has been infected, what should you do first?",
            type: "radio",
            required: true,
            choices: [
              "Disconnect from the internet",
              "Continue using it",
              "Ignore the issue",
              "Download random cleaning software",
            ],
          },
        ],
      },
      {
        id: "confidence",
        title: "CyberSecurity Section 3: Cybersecurity Confidence",
        description: "Use the 1–5 scale below for each statement.",
        questions: [
          {
            id: "conf_phishing",
            entry: "entry.1099657759",
            question: "I am confident in identifying phishing attempts.",
            type: "radio",
            required: true,
            choices: ["1", "2", "3", "4", "5"],
          },
          {
            id: "conf_info",
            entry: "entry.1745437936",
            question: "I know how to protect my personal information online.",
            type: "radio",
            required: true,
            choices: ["1", "2", "3", "4", "5"],
          },
          {
            id: "conf_threat",
            entry: "entry.88328170",
            question: "I know the appropriate actions to take after encountering a cybersecurity threat.",
            type: "radio",
            required: true,
            choices: ["1", "2", "3", "4", "5"],
          },
        ],
      },
    ],
  },
  posttest: {
    id: "posttest",
    title: "2Phishy: Post-test Assessment",
    subtitle: "Measure knowledge and learning experience after using 2Phishy.",
    intro: [
      "We are third-year BS Information Technology students from Mapúa University – Makati Campus conducting our thesis entitled \"2Phishy: A Gamified Learning Application for Cybersecurity Awareness.\"",
      "Thank you for participating in the 2Phishy playtest. This post-playtest questionnaire aims to evaluate your cybersecurity knowledge, awareness, and learning experience after using the 2Phishy application.",
      "Please answer each question honestly based on your current knowledge and your experience while using 2Phishy.",
    ],
    completionCopy:
      "Your post-test response has been saved to the research backend and queued for Google Forms backup.",
    googleFormsEndpoint:
      "https://docs.google.com/forms/d/e/1FAIpQLSd3QliZOYKICcbaOIcvXFOp--sv9Rf3fXqeau2boySgaOFj5g/formResponse",
    steps: [
      {
        id: "consent",
        title: "Data Privacy Agreement",
        questions: [
          {
            id: "consent",
            entry: "entry.511338609",
            googleFormsEntry: "entry.511338609_sentinel",
            question:
              "I am aware of my rights and the responsibilities of the researchers regarding the management of my data. I hereby grant permission for this group's researchers to use the information I will provide on this form for the purposes of this study.",
            type: "radio",
            required: true,
            choices: ["I agree with terms and conditions outlined above"],
          },
        ],
      },
      {
        id: "participant-profile",
        title: "Participant Profile",
        questions: [
          {
            id: "participant_id",
            entry: "entry.907467691",
            question: "Participant ID",
            type: "short_answer",
            required: true,
            placeholder: "Please ask the facilitator if unknown",
            helperText: "If you are unsure, ask the facilitator before continuing.",
          },
        ],
      },
      {
        id: "knowledge",
        title: "CyberSecurity Section 2: General Cybersecurity Knowledge",
        questions: [
          {
            id: "padlock_icon",
            entry: "entry.1673979401",
            question: "What does the padlock icon beside a website's address usually indicate?",
            type: "radio",
            required: true,
            choices: [
              "The website is safe from malware",
              "The connection is encrypted using HTTPS",
              "The website is government-approved",
              "The website has no advertisements",
            ],
          },
          {
            id: "password_security",
            entry: "entry.629643857",
            question: "Which practice improves password security the most?",
            type: "radio",
            required: true,
            choices: [
              "Reusing one password",
              "Using long, unique passwords for each account",
              "Sharing passwords with trusted friends",
              "Writing passwords on paper beside your computer",
            ],
          },
          {
            id: "verify_bank_email",
            entry: "entry.1958849132",
            question: "Which is the best way to verify an email claiming to be from your bank?",
            type: "radio",
            required: true,
            choices: [
              "Click the provided link",
              "Contact the bank using its official contact information",
              "Reply to the email",
              "Ignore every bank email",
            ],
          },
          {
            id: "ransomware",
            entry: "entry.70721282",
            question: "What does ransomware do?",
            type: "radio",
            required: true,
            choices: [
              "Encrypts files and demands payment",
              "Speeds up your computer",
              "Blocks advertisements",
              "Creates stronger password",
            ],
          },
          {
            id: "social_engineering",
            entry: "entry.527102369",
            question: "Which is an example of social engineering?",
            type: "radio",
            required: true,
            choices: [
              "Tricking users into revealing confidential information",
              "Updating antivirus software",
              "Encrypting internet traffic",
              "Creating secure passwords",
            ],
          },
          {
            id: "personal_info",
            entry: "entry.1904816629",
            question: "Which action best protects your personal information online?",
            type: "radio",
            required: true,
            choices: [
              "Sharing personal details only when necessary",
              "Posting all information publicly",
              "Using the same password everywhere",
              "Accepting every permission request",
            ],
          },
          {
            id: "suspicious_activity",
            entry: "entry.1048288850",
            question: "After discovering suspicious activity on your account, what should you do first?",
            type: "radio",
            required: true,
            choices: [
              "Change your password and report the incident",
              "Ignore it",
              "Share your password with friends",
              "Delete your browser",
            ],
          },
        ],
      },
      {
        id: "confidence",
        title: "CyberSecurity Section 3: Cybersecurity Confidence",
        description: "Use the 1–5 scale below for each statement.",
        questions: [
          {
            id: "conf_phishing",
            entry: "entry.1099657759",
            question: "I am confident in identifying phishing attempts.",
            type: "radio",
            required: true,
            choices: ["1", "2", "3", "4", "5"],
          },
          {
            id: "conf_info",
            entry: "entry.1745437936",
            question: "I know how to protect my personal information online.",
            type: "radio",
            required: true,
            choices: ["1", "2", "3", "4", "5"],
          },
          {
            id: "conf_threat",
            entry: "entry.88328170",
            question: "I know the appropriate actions to take after encountering a cybersecurity threat.",
            type: "radio",
            required: true,
            choices: ["1", "2", "3", "4", "5"],
          },
        ],
      },
      {
        id: "game-experience",
        title: "Section 4: Game Experience",
        questions: [
          {
            id: "game_engagement",
            entry: "entry.253549919",
            question: "How engaging did you find the game?",
            type: "radio",
            required: true,
            choices: [
              "Very Engaging",
              "Somewhat Engaging",
              "Neutral",
              "Not Engaging",
              "Very Unengaging",
            ],
          },
          {
            id: "learning_component",
            entry: "entry.1452349600",
            question: "Which game component contributed the most to your learning?",
            type: "radio",
            required: true,
            choices: [
              "Interactive challenges",
              "Storyline",
              "NPC interactions",
              "Educational explanations",
              "Scenario-based decision making",
            ],
          },
          {
            id: "learned_topic",
            entry: "entry.887819345",
            question: "Which cybersecurity topic do you think you learned the most?",
            type: "radio",
            required: true,
            choices: [
              "Safe Browsing",
              "Password Security",
              "Malware",
              "Social Engineering",
              "Incident Response",
            ],
          },
          {
            id: "awareness_improved",
            entry: "entry.407570034",
            question: "Do you feel that playing 2Phishy improved your cybersecurity awareness?",
            type: "radio",
            required: true,
            choices: [
              "Strongly Agree",
              "Agree",
              "Neutral",
              "Disagree",
              "Strongly Disagree",
            ],
          },
          {
            id: "recommend_tool",
            entry: "entry.48342652",
            question: "Would you recommend 2Phishy as a cybersecurity learning tool to other students?",
            type: "radio",
            required: true,
            choices: ["Definitely Yes", "Probably Yes", "Not Sure", "Probably No", "Definitely No"],
          },
        ],
      },
    ],
  },
};
