services:

  postgres:
    image: postgres:15
    container_name: phishy-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: phishy_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mongo:
    image: mongo:6
    container_name: phishy-mongo
    command: ["mongod", "--auth"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: MonAndreJahnAmarillento
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  redis:
    image: redis:7
    container_name: phishy-redis
    command: redis-server --requirepass SumbunganNgHotdog
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    container_name: phishy-backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

    volumes:
      - ./backend:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - mongo
      - redis

  frontend:
    image: node:20
    container_name: phishy-frontend
    working_dir: /app
    volumes:
      - ./2Phishy/image-display-app:/app
    command: sh -c "npm install && npm start"
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped


volumes:
  postgres_data:
  mongo_data:
  redis_data:
