services:
  phishy-progress-tool:
    build: .
    container_name: phishy-progress-tool
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "127.0.0.1:8088:8080"
    networks:
      - deploy_default

networks:
  deploy_default:
    external: true
